/* Generated By:JavaCC: Do not edit this line. PlottingLanguageConstants.java */
package org.eclipse.linuxtools.internal.tmf.ui.graph.language;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface PlottingLanguageConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int LEFT_PARENTHESIS = 9;
  /** RegularExpression Id. */
  int RIGHT_PARENTHESIS = 10;
  /** RegularExpression Id. */
  int EVENT = 11;
  /** RegularExpression Id. */
  int PREVIOUS = 12;
  /** RegularExpression Id. */
  int TIMESTAMP = 13;
  /** RegularExpression Id. */
  int RANK = 14;
  /** RegularExpression Id. */
  int IDENTIFIER = 15;
  /** RegularExpression Id. */
  int LETTER = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 18;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 19;
  /** RegularExpression Id. */
  int HEX_LITERAL = 20;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 21;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 22;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 23;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 24;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"event\"",
    "\"previous\"",
    "\"timestamp\"",
    "\"rank\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "\".\"",
  };

}
